# Staking Ledger Allocations in YAML so we can comment as needed

# This file is a simple "key": "value" where key is the github name and the
# value is the quantity of tokens to assign. The tokens are whole tokens so
# when they're translated in the staking ledger they will be multiplied by 1e9
accounts:
  backers:
    amount: "2300000000"
    address: "oasis1qz2kz3zkgf6trclyajtyg4jecw7es7p5tutfqaz0"
    outbound_delegations: {}

  community_and_ecosystem:
    amount: "2300000000"
    address: "oasis1qqfjknq5jlelnfd0xtc38u9t25u467nasuzytpe3"
    outbound_delegations: {}

  core_contributors:
    amount: "2000000000"
    address: "oasis1qzpjtg2zhqqun6nmvclrtdmwuxeluj6pxgvedwzu"
    outbound_delegations: {}

  strategic_partners_and_reserve:
    amount: "500000000"
    address: "oasis1qpn5qckl50vfn0phmn545ufrypvfqqzhwgaprxv5"
    outbound_delegations: {}

  foundation_endowment:
    amount: "1000000000"
    address: "oasis1qpu9qf32765nl5ql8jkh6zmrlwvu23srecu5phac"
    outbound_delegations: {}

# This should be a dict of expected entity packages
entities:
  Alexxxandr0: "10000"
  Bambarello: "10000"
  C-Surgeon: "10000"
  CentreDLTUM: "10000"
  Code-Breader: "10000"
  Julia-Ju-Ju: "10000"
  Karmastic: "10000"
  LRUki_LBL_Imperial: "10000"
  LRUki_LBL_LSE: "10000"
  LRUki_LBL_UCL: "10000"
  PowerMax999: "10000"
  SebastianJ: "10000"
  Shella: "10000"
  SimplyVC: "10000"
  SmartStake: "10000"
  UbikCapital: "10000"
  Wanderer-Cry: "10000"
  WolfEdgeCapital: "10000"
  ank-everstake: "10000"
  ankr-danielimkk: "10000"
  aptemuyc: "10000"
  bab-danielimkk: "10000"
  ben-staked: "10000"
  bitoven-dev: "10000"
  blockdaemon-mainnet: "10000"
  blockdev345: "10000"
  calvinzhou-rockx: "10000"
  caramis: "10000"
  chadbean: "10000"
  cherideal: "10000"
  chorus-techops: "10000"
  chris-remus: "10000"
  codernpm: "10000"
  culmore2015: "10000"
  dcccapital: "10000"
  defunctzombie: "10000"
  dm4: "10000"
  elsehow: "10000"
  flankerted: "10000"
  flutterwin: "10000"
  frankfurt-school-mainnet: "10000"
  gunray88: "10000"
  himansh987: "10000"
  huglester: "10000"
  hydai: "10000"
  jjangg96: "10000"
  joesixpack: "10000"
  jrastit: "10000"
  k0kk0k: "10000"
  kaustubhkapatral: "10000"
  keefertaylor: "10000"
  kwunyeung: "10000"
  lqyice: "10000"
  lymweb: "10000"
  lyoungblood: "10000"
  m4dbi7: "10000"
  marssuper: "10000"
  mattharrop: "10000"
  mit-digital-currency-initiative-mainnet: "10000"
  mohakagr: "10000"
  oceanabcde: "10000"
  pkrasam: "10000"
  ponchik69: "10000"
  privatenerd: "10000"
  sili-infstones: "10000"
  spdd: "10000"
  sriney-staked: "10000"
  validator01: "10000"
  wetezos: "10000"
  winslyn: "10000"
  wjdfx: "10000"
  xudoubles: "10000"
  y3v63n: "10000"

##
# BELOW ARE FUNDING ALLOCATIONS FOR TEST ONLY GENESIS DOCUMENTS
##
test_entities:
  rvg: "100000"
  #pro-wh: "100000"
  peterjgilbert: "100000"

# This is the minimum balance that should be left in an account
minimum_balance: 100
token_value_exponent: 9
token_symbol: ROSE
total_supply: 10000000000

commission_rate_max: 20000
commission_rate_min: 0
commission_rate: 5000
